# Generated by Django 2.2 on 2020-07-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='sandy', max_length=255),
            preserve_default=False,
        ),
    ]
